I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/character_intros.rpy", line 15, in script
    chad "Yo, I'm Chad!"
Exception: Sayer 'chad' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/character_intros.rpy", line 15, in script
    chad "Yo, I'm Chad!"
  File "C:\Users\ariel\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\ariel\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'chad' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Charmer 1.0
Thu Dec 28 20:01:03 2023
